[package]
name = "rusty_roguelike"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bracket-lib = "~0.8.1"
legion = "=0.4.0"
dry-mods = "0.1.5"
serde = { version = "1.0.*" }
ron = "=0.8.1"
